# Generated by Django 4.0.4 on 2022-05-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_notes_title_notes_alter_notes_content_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category_notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='development.category_notes', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content_notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_at_notes',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='photo_notes',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title_notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
