# Generated by Django 4.0.4 on 2022-05-16 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_theme_article', models.CharField(db_index=True, max_length=150, verbose_name='Наименование темы статьи')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статей',
                'ordering': ['title_theme_article'],
            },
        ),
        migrations.CreateModel(
            name='Theme_review_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_theme_review', models.CharField(db_index=True, max_length=150, verbose_name='Наименование темы обзора на книг')),
            ],
            options={
                'verbose_name': 'Тема статьи',
                'verbose_name_plural': 'Темы статей',
                'ordering': ['title_theme_review'],
            },
        ),
        migrations.CreateModel(
            name='Book_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(max_length=100, verbose_name='Название книги для обзора')),
                ('text_review', models.TextField(blank=True, max_length=10000, verbose_name='Текст обзора книги')),
                ('author_review', models.CharField(max_length=30, verbose_name='Автор книги с обзора')),
                ('created_at_review', models.DateTimeField(auto_now_add=True, verbose_name='Обзор книги создан')),
                ('photo_review', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото книги с обзора')),
                ('theme_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.theme_review_book', verbose_name='Тема книги с обзора')),
            ],
            options={
                'verbose_name': 'Обзор книги',
                'verbose_name_plural': 'Обзоры книг',
                'ordering': ['-created_at_review'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_article', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('content_article', models.TextField(blank=True, max_length=10000, verbose_name='Текст статьи')),
                ('created_at_article', models.DateTimeField(auto_now_add=True, verbose_name='Статья создана')),
                ('photo_article', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото статьи')),
                ('is_published_article', models.BooleanField(default=True, verbose_name='Публиковать статью')),
                ('theme_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.theme_article', verbose_name='Тема статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at_article'],
            },
        ),
    ]
