# Generated by Django 4.0.4 on 2022-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_theme_review_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_article',
            field=models.IntegerField(default=0),
        ),
    ]
